# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a43d0735b543caa94f8fa3c0c5cb856cf91f633669e81523db7cf2c7f3e31e8aaffc82f52cb24f3e420ea4c3bc3f42250d6f00b7c2e65a9627e579815697cb5

test:
  secret_key_base: 88fb1d3ada92bd2632f824c538414c2bfa8160f569752d4ed761047fdfa7d2f1efd62bf93ee0ea836f345389df7d0a53f88be4596ff488b37ffc33f04a0a000f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
